<?php
// $Id$

/**
 * @file
 * The main module file for workflow_og module.
 */
 
 
 /**
 * Implementation of hook_perm().
 */
function workflow_og_perm() {
  return array(
    'promote workflow_og'
  );
}

/**
 * Implementation of hook_menu().
 */
function workflow_og_menu() {
 $items['node/%/promote'] = array(
    'title' => t('Promote'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('workflow_og_og_audience'),
    'access callback' => TRUE,
    'description' => t('Promote to group'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'workflow_og.og_audience.inc',
  );


  return $items;
}



